# SQL Analyzer Enterprise - Development Configuration
# Developer-friendly configuration with debugging and hot reload

server:
  host: "127.0.0.1"
  port: 8081
  workers: 2
  debug: true
  reload: true
  log_level: "DEBUG"
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
    - "http://127.0.0.1:3000"
    - "http://127.0.0.1:8080"

database:
  host: "localhost"
  port: 5432
  database: "sql_analyzer_dev"
  username: "dev_user"
  password: "dev_password"
  pool_size: 5
  max_overflow: 10
  pool_timeout: 30

security:
  jwt_secret: "dev-secret-key-not-for-production"
  session_timeout: 7200  # 2 hours for development
  max_login_attempts: 10  # More lenient for development
  password_min_length: 4  # Shorter for development
  enable_2fa: false
  encryption_enabled: false  # Disabled for easier debugging

processing:
  max_file_size: 104857600  # 100MB
  max_concurrent_files: 3
  chunk_size: 8192
  supported_formats:
    - ".sql"
    - ".txt"
    - ".pdf"
    - ".csv"
    - ".json"
    - ".log"  # Additional formats for development
  temp_dir: "temp_dev"
  output_dir: "output_dev"

analysis:
  enable_syntax_check: true
  enable_security_scan: true
  enable_performance_analysis: true
  enable_schema_analysis: true
  max_analysis_time: 120  # 2 minutes for faster development
  parallel_analysis: false  # Easier debugging with sequential processing

logging:
  level: "DEBUG"
  file: "logs/sql_analyzer_dev.log"
  max_size: "10MB"
  backup_count: 3
  format: "%(asctime)s - %(name)s - %(levelname)s - %(funcName)s:%(lineno)d - %(message)s"

monitoring:
  enable_metrics: false  # Disabled for development
  metrics_port: 9091
  health_check_interval: 60
  performance_monitoring: false

backup:
  enable_auto_backup: false  # Disabled for development
  backup_interval: 86400  # 24 hours
  backup_retention: 24  # 1 day
  backup_location: "backups_dev"

cache:
  enable_redis: false  # Use in-memory cache for development
  redis_host: "localhost"
  redis_port: 6379
  redis_db: 1
  cache_ttl: 1800  # 30 minutes

email:
  smtp_server: "localhost"
  smtp_port: 1025  # MailHog or similar for development
  smtp_username: ""
  smtp_password: ""
  use_tls: false
  from_address: "SQL Analyzer Dev <dev@localhost>"

rate_limiting:
  enable: false  # Disabled for development
  requests_per_minute: 1000
  requests_per_hour: 10000
  burst_limit: 2000

ssl:
  enable: false  # HTTP for development
  cert_file: ""
  key_file: ""
  ca_file: ""

# Development-specific settings
development:
  auto_reload_templates: true
  show_sql_queries: true
  enable_debug_toolbar: true
  mock_external_services: true
  test_data_enabled: true
  profiling_enabled: true
