# SQL Analyzer Enterprise - Production Configuration
# High-performance, secure configuration for production deployment

server:
  host: "0.0.0.0"
  port: 8081
  workers: 8
  debug: false
  reload: false
  log_level: "WARNING"
  cors_origins:
    - "https://sqlanalyzer.com"
    - "https://www.sqlanalyzer.com"
    - "https://app.sqlanalyzer.com"

database:
  host: "db.sqlanalyzer.com"
  port: 5432
  database: "sql_analyzer_prod"
  username: "sql_analyzer_user"
  password: "${DB_PASSWORD}"  # Use environment variable
  pool_size: 20
  max_overflow: 40
  pool_timeout: 60

security:
  jwt_secret: "${JWT_SECRET}"  # Use environment variable
  session_timeout: 1800  # 30 minutes
  max_login_attempts: 3
  password_min_length: 12
  enable_2fa: true
  encryption_enabled: true

processing:
  max_file_size: 10737418240  # 10GB
  max_concurrent_files: 20
  chunk_size: 16384
  supported_formats:
    - ".sql"
    - ".txt"
    - ".pdf"
    - ".csv"
    - ".json"
  temp_dir: "/var/tmp/sql_analyzer"
  output_dir: "/var/data/sql_analyzer/output"

analysis:
  enable_syntax_check: true
  enable_security_scan: true
  enable_performance_analysis: true
  enable_schema_analysis: true
  max_analysis_time: 600  # 10 minutes
  parallel_analysis: true

logging:
  level: "INFO"
  file: "/var/log/sql_analyzer/app.log"
  max_size: "100MB"
  backup_count: 10
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

monitoring:
  enable_metrics: true
  metrics_port: 9090
  health_check_interval: 30
  performance_monitoring: true

backup:
  enable_auto_backup: true
  backup_interval: 3600  # 1 hour
  backup_retention: 168  # 7 days
  backup_location: "/var/backups/sql_analyzer"

cache:
  enable_redis: true
  redis_host: "cache.sqlanalyzer.com"
  redis_port: 6379
  redis_db: 0
  cache_ttl: 3600  # 1 hour

email:
  smtp_server: "smtp.sqlanalyzer.com"
  smtp_port: 587
  smtp_username: "noreply@sqlanalyzer.com"
  smtp_password: "${SMTP_PASSWORD}"
  use_tls: true
  from_address: "SQL Analyzer <noreply@sqlanalyzer.com>"

rate_limiting:
  enable: true
  requests_per_minute: 100
  requests_per_hour: 1000
  burst_limit: 200

ssl:
  enable: true
  cert_file: "/etc/ssl/certs/sqlanalyzer.crt"
  key_file: "/etc/ssl/private/sqlanalyzer.key"
  ca_file: "/etc/ssl/certs/ca-bundle.crt"
